Cloud bastion
Otus-DevOps-2022-05/Turdalievw_infra pull request #11
Opened 2022-06-23 09:40 UTC by Turdalievw

2022-06-23 15:15 UTC, mrgreyves requested changes
Добавляем описание к пуллреквесту
<img width="927" alt="image" src="https://user-images.githubusercontent.com/34331259/175333957-e15a1111-8717-498f-9c36-f6f5497d35b7.png">

2022-06-24 08:26 UTC, Turdalievw commented
cloud-bastion
Создал две машины в yndex cloud , одна с public ip, вторая с internal ip.
Cделал подключение по ssh по alias - ssh someinternalhost, для сквозного подключения на сервер без публичного адреса.

На сервере Bastion сделал VPN Pritunl с пользователем test.

2022-07-04 18:48 UTC, Turdalievw commented
Закройте плиз это задание

2022-07-04 19:08 UTC, mrgreyves approved these changes
Здравствуйте!)
Без проблем, сейчас все хорошо =)

2022-07-04 19:13 UTC, merged